### ISSUE TITLE
Failed to resolve: org.glud.trascendentAR:trascendentAR-android:1.0-beta.1

### ISSUE THREAD

**Issue by GianUPN** [GLUD/trascendentAR#6]
Tengo ese problema cuando trato de crear mi proyecto. Como puedo solucionarlo???

**Comment by GianUPN** [comment]
Added jcenter() to gradle, but now I got this problem....
Failed to resolve: gdx-ar:aRBaseLib:1.0

**Comment by Juankz** [comment]
Voy a darle un vistazo, estás usando Android Studio o IntelliJ IDEA?

**Comment by Juankz** [comment]
Bueno, al parecer gradle no podía encontrar el repositorio donde está alojado el .aar de artoolkit. 
Agrega las siguientes líneas al archivo `build.gradle` que se encuentra en la raíz del proyecto:

```groovy
allprojects {
   ...
    repositories {
       ...
        //Agregar estas dos líneas
        jcenter()
        maven { url "https://dl.bintray.com/juankz/trascendentAR/" }
    }
}
```

Me comentas si funcionó

**Comment by GianUPN** [comment]
Funcionó :+1:
